platform :ios, '12.0'

use_frameworks!
use_modular_headers!

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

flutter_application_path = File.expand_path('..', __dir__)
eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')), binding)
